<a href="https://colab.research.google.com/github/robertosgpontes/tec_prog_1/blob/main/ExerciciosNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lista de Exercícios de Numpy

Deverá ser entrege até **11/02/2023** por meio do github que foi informado por vocês no [formulário](https://forms.office.com/r/YV12vEXGYF) respondido na aula de 01/02.

A entrega pela github é parte da avaliação.

## Questão 1

Crie um array 100 com valores aleatórios e ache os valores máximo e mínimo

In [1]:
import numpy as np
np.random.seed(23)
array_1=np.random.randint(0,100,size=100)
print(array_1)
print('O valor máximo é: ',max(array_1))
print('O valor mínimo é: ',min(array_1))

[83 40 73 54 31 76 91 39 90 25 51  6 45 12 49 66 75 85 69 64 12 21 48 41
 79 90 62 57 19 33 59 39 15 36 65  1 43 15 86 83 58 25 66 74 35 96 56 13
 60 22 38 31 94 78  0 21  6 32 98 32 14 31 78 83 80 70 66 82 85 55 27 62
 43 74 71 42 83 21  6 68 22 43  8 85 62 32 60 11  1 41 26 37 41 56 39 81
 32 53 35 23]
O valor máximo é:  98
O valor mínimo é:  0


## Questão 2
Em Geometria Analítica, um **vetor** é uma quantidade que pode ser definida por um énuplo (uma sequência ordenada de *n* elementos) em que cada elemento representa a intensidade do vetor na direção especificada pela i-ésima componente desta sequência. 

Quando pensamos em duas dimensões, por exemplo, o vetor $R = (b,a)$ define, geometricamente, a entidade representada na figura abaixo, com componentes nos eixos x e y usuais.

<img src = "https://static.todamateria.com.br/upload/im/ag/image-721.jpg?auto_optimize=low" />

O **módulo** deste vetor, também chamado de intensidade, está geometricamente relacionado ao seu comprimento, e pode ser calculado diretamente pelas suas componentes, por meio de uma operação conhecida como **produto escalar** do vetor com ele mesmo. O módulo quadrático é expresso, desta forma, por:

$|A|^2 = \vec{A} \cdot \vec{A}$

Por outro lado, o produto escalar entre dois vetores $A = (a_{x}, a_{y})$ e $B = (b_{x}, b_{y})$ é dado por:

$\vec{A} \cdot \vec{B} = a_{x} \times b_{x} + a_{y} \times b_{y}$ (e esta definição vale para qualquer que seja a dimensão do vetor).

O módulo quadrático de um vetor é, portanto:

$|A|² = a_{x}^2 + b_{x}^2$.

Dado o exposto acima, escreva uma função que retorne o módulo de um vetor n-dimensional qualquer.

In [8]:

import numpy as np

# Definindo o tamanho do vetor
tamanho_vetor = np.random.randint(15) 

# Criando o vetor
vetor_aleatorio = np.random.randint(0, 100, tamanho_vetor)

def calculo_modulo(x):
  soma=0
  for i in range(len(x)):
    soma=soma+x[i]**2
  modulo=np.sqrt(soma)
  return modulo
print('O vetor é:',vetor_aleatorio)
print('O módulo é:',calculo_modulo(vetor_aleatorio))
    

O vetor é: [96 44 83 27 44 91 49 41  6]
O módulo é: 181.94779471046084


## Questão 3

Em uma **análise de regressão**, usualmente estamos interessados em descrever relações entre variáveis de um dado conjunto de dados por meio de uma **função** que descreva, o tanto quanto possível, estas relações.

Por exemplo, no gráfico abaixo, os pontos vermelhos relacionam as medidas das duas variáveis sendo avaliadas (nos eixos x e y); e a linha azul aproxima a relação entre elas por uma função linear.

![Normdist_regression.png](https://miro.medium.com/v2/resize:fit:786/format:webp/1*LEmBCYAttxS6uI6rEyPLMQ.png)

É possível ver que nem todos os pontos obedecem exatamente à relação ditada pela reta (isto é, há pontos que não estão exatamente "sobre a reta"; mas, sim, ligeraimente acima, ou abaixo, dela). Isto, contudo, é esperado em um modelo de regressão, por inúmeras fontes de incerteza associadas às medições.

Uma das métricas que utilizamos para avaliar a qualidade de uma regressão é o **erro quadrático médio (EQM)**, que mensura a diferença total entre cada predição da regressão ($y_{prediction}$; que no nosso caso seriam os valores de y para a reta azul) com o valor real de cada i-ésima medida ($y_{i}$; que no nosso caso seriam as coordenadas y para cada ponto vermelho do gráfico). O EQM pode ser definido como:

$EQM = \frac{1}{n}\sum_{i=1}^{n}(y_{prediction} - y_{i})^2$.

Isto posto, escreva uma função que calcule o EQM recebendo, como entrada, os vetores $y_{prediction}$ e $y_{i}$. Por exemplo, digamos que sua função se chame *calculate_eqm*, ela deve operar da seguinte forma:

In [64]:
import numpy as np
n_1=np.random.randint(10)
y_pred=np.random.randint(0,10,n_1)
y_real=np.random.randint(0,10,n_1)
def EQM_calculate(y_pred,y_real):
    soma=0
    n_tamanho=len(y_pred)
    for i in range(0,n_tamanho):    
        dif=(y_pred[i]-y_real[i])**2
        soma=soma+dif
    EQM=(1/n_tamanho)*soma
    return print('O EQM é:',EQM)
EQM_calculate(y_pred,y_real)
print('Real:\n',y_real)
print('Predição:\n',y_pred)


O EQM é: 6.833333333333333
Real:
 [6 4 5 8 4 0]
Predição:
 [7 0 1 6 6 0]


## Questão 4

Crie um array 2D (bidimensional) com 1 na borda e 0 dentro

In [44]:
import numpy as np
#criando uma matriz de zeros 5x5
array_0=np.zeros((5,5))
#substituindo os valores:
for i in range(0,5):
    array_0[0,i]=1
for j in range(0,5):
    array_0[j,0]=1
for k in range(0,5):
    array_0[4,k]=1
for l in range(0,5):
    array_0[l,4]=1
array_0

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## Questão 5

Como adicionar uma borda de 0's ao redor de um array 2D (bidimensional) existente

In [139]:
import numpy as np
n=np.random.randint(10)
array_bidimensional=np.random.randint(0,10,(n,n))
array_bordas=np.zeros((n+2,n+2),dtype=np.int32)
for i in range (0,n):
    for j in range(0,n):
        array_bordas[i+1,j+1]=array_bidimensional[i,j]

print('Array original:\n',array_bidimensional)
print('Array com bordas:\n',array_bordas,)

Array original:
 [[0 1 1 6 6 2 7 0]
 [1 3 4 8 4 7 1 3]
 [9 1 4 9 6 2 0 4]
 [4 0 7 8 8 5 5 2]
 [8 9 7 2 4 5 5 4]
 [3 8 1 2 2 0 5 0]
 [0 1 0 1 7 5 1 9]
 [5 5 3 7 9 3 7 0]]
Array com bordas:
 [[0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 6 6 2 7 0 0]
 [0 1 3 4 8 4 7 1 3 0]
 [0 9 1 4 9 6 2 0 4 0]
 [0 4 0 7 8 8 5 5 2 0]
 [0 8 9 7 2 4 5 5 4 0]
 [0 3 8 1 2 2 0 5 0 0]
 [0 0 1 0 1 7 5 1 9 0]
 [0 5 5 3 7 9 3 7 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


## Questão 6

 A eletroencefalografia (EEG) é uma técnica que mensura potenciais elétricos cerebrais em diversas regiões do escalpo do paciente. Suponha que você recebeu um conjunto de dados na forma de uma matriz de 64 x 512 elementos, em que cada linha contém o sinal gravado em um dos **eletrodos** espalhados pelo escalpo em um exame de EEG, e cada coluna contém um valor de potencial elétrico, em microvolts. 

Como o sinal de EEG é muito suscetível a ruídos externos (interferências na qualidade do sinal), uma operação comum para atenuar a interferência no sinal consiste em tirar a média do potencial elétrico de todos os eletrodos, e subtrair este valor de cada um deles. Isto atenua fontes de ruído ao sinal comuns a todos os eletrodos. Em termos matemáticos, o sinal processado por esta operação, $X_{e,i}$ para cada eletrodo (e) e amostra (i), é dado por:

$X_{e,i} = \hat{X_{e,i}} - \frac{1}{N}\sum_{e=1}^{N}\hat{X_{e,i}}$,

em que $\hat{X_{e,i}}$ representa o sinal original (ou seja, é a matriz de entrada de 64 x 512 elementos), e $N$ indica o total de eletrodos.

Com o exposto acima, escreva uma função que retorne uma matriz com os sinais de EEG processados conforme a operação mencionada. Sua função deve operar conforme o exemplo abaixo.

In [66]:
# vamos supor uma matriz de entrada gerada por dados aleatórios
X = np.random.randn(64,512)
X.shape # apenas para verificar as dimensões

(64, 512)

In [ ]:
# a função deve executar a operação equacionada anteriormente, retornando uma nova matriz
X_processado = process_EEG_signal(X)
X_processado.shape

(64, 512)

In [ ]:
# Somando as diferenças entre cada elemento das duas matrizes, apenas para ilustrar que elas não são iguais
(X_processado - X).sum()

-53.08727366483029

In [ ]:
# Visualizando as matrizes, para verificar uma vez mais que, de fato, os elementos são diferentes
X

array([[ 0.29305925,  0.89663038, -0.61032202, ..., -0.88086364,
        -0.8818789 ,  0.51260497],
       [-0.01274415,  1.05439522,  0.47958092, ..., -2.15387924,
         0.70721168,  0.97029889],
       [ 1.09478371, -0.16120847,  1.58400361, ...,  0.20981813,
         2.17373837,  0.94032162],
       ...,
       [-0.45294842, -2.28939505,  1.10111998, ...,  1.63581703,
        -0.39394924, -1.13400723],
       [-0.22669886,  0.25413429, -1.17870637, ..., -0.09509442,
         0.90733806,  0.37999411],
       [ 0.15476933, -0.03654717, -1.09982762, ...,  0.67600047,
        -0.84533328, -0.56433144]])

In [ ]:
# Matriz após o processamento descrito no enunciado
X_processado

array([[ 0.36713022,  0.85772513, -0.54902169, ..., -0.85626087,
        -0.97611435,  0.51718998],
       [ 0.06132682,  1.01548997,  0.54088126, ..., -2.12927647,
         0.61297623,  0.97488389],
       [ 1.16885469, -0.20011372,  1.64530394, ...,  0.23442091,
         2.07950292,  0.94490663],
       ...,
       [-0.37887744, -2.3283003 ,  1.16242031, ...,  1.6604198 ,
        -0.4881847 , -1.12942223],
       [-0.15262788,  0.21522904, -1.11740604, ..., -0.07049164,
         0.81310261,  0.38457911],
       [ 0.22884031, -0.07545242, -1.03852729, ...,  0.70060324,
        -0.93956874, -0.55974643]])

In [73]:
import numpy as np
eletrodos_matriz=np.random.randn(64,512)
def processado_eletrodo(x):
    med=x.mean()
    eletrodos_processados= x - med
    return eletrodos_processados
print('A matriz é:\n',eletrodos_matriz)
print('A matriz processada é:\n', processado_eletrodo(eletrodos_matriz))
     

A matriz é:
 [[ 0.39750721  0.66563458  1.27525101 ...  0.34447363  0.16978808
   0.44923627]
 [-0.89096427 -0.42060423  0.87255931 ... -0.45956737  1.1840446
  -0.97774097]
 [-0.99368489 -1.17616223 -0.54150518 ...  0.40021544  2.00463622
   0.3268071 ]
 ...
 [-0.54603609 -1.91451914 -0.31597106 ... -1.32785349 -0.73288359
   0.4800148 ]
 [-1.1047308   1.14445422 -1.52661976 ... -0.76457661 -0.98691355
   0.17837241]
 [ 0.85543841  0.31775047 -0.31038382 ... -0.53007017 -0.07929101
  -1.5446027 ]]
A matriz processada é:
 [[ 0.38959225  0.65771962  1.26733605 ...  0.33655867  0.16187312
   0.4413213 ]
 [-0.89887923 -0.42851919  0.86464435 ... -0.46748234  1.17612964
  -0.98565594]
 [-1.00159985 -1.18407719 -0.54942015 ...  0.39230047  1.99672126
   0.31889213]
 ...
 [-0.55395105 -1.9224341  -0.32388603 ... -1.33576845 -0.74079856
   0.47209983]
 [-1.11264577  1.13653926 -1.53453473 ... -0.77249158 -0.99482852
   0.17045744]
 [ 0.84752345  0.30983551 -0.31829878 ... -0.53798513 -0.08720

## Questão 7

Em estatística, um **outlier** é um valor que destoa consideravelmente da distribuição à qual está associado. Um dos critérios para idenficar outliers consiste em encontrar a **distância interquantil** (IQR), ou seja, a diferença entre o terceiro (Q3) e o primeiro quartis (Q1) da distribuição, e tomar como outliers todos os pontos abaixo de 1.5*IQR - Q1, ou acima de 1.5*IQR + Q3.

<img src = "https://blog.curso-r.com/images/posts/banner/outlier.webp" />

Escreva uma função que, dada uma matriz de dados de entrada de dimensões $N_{observações} \times N_{features}$ retorne três requisitos: 
- uma matriz booleana indicando a existência de outliers nos dados de entrada;
- a quantidade de outliers
- quem são os outliers (os valores).

**Algumas definições:**
- um *quantil* divide a distribuição, após ordenados os pontos, segundo algum ponto de corte;
- o **primeiro quartil** é o ponto para o qual 25 % dos valores da distribuição estão abaixo dele;
- o **terceiro quartil** é o ponto para o qual 75 % dos valores da distribuição estão abaixo dele.

Pode ser útil consultar a função **numpy.quantile**.

Exemplo de operação da função:

In [ ]:
# Geremos um conjunto de dados qualquer
X = np.random.randn(300,15)
X

array([[-2.02108952,  0.57945921, -2.23074965, ..., -0.60349514,
         0.92180452, -0.15625722],
       [ 0.24904397,  0.03493447,  0.3515052 , ..., -0.46950081,
         0.20361331,  0.02715956],
       [ 0.55902525, -0.48435434,  0.90413414, ..., -0.54425743,
        -0.80769134, -0.07912549],
       ...,
       [-1.04069388, -0.24245725, -2.00308877, ...,  0.4084777 ,
        -1.81516131,  0.39063118],
       [-1.39275097,  0.3989636 ,  0.2926223 , ...,  1.2620666 ,
         0.72262949,  1.50737559],
       [ 0.15922011, -0.79810788, -1.60939896, ..., -0.08214499,
        -0.13167475,  0.15990558]])

In [ ]:
# identificamos os requisitos com nossa com nossa função "locate_outliers"
is_outlier, outliers_count, outliers = locate_outliers(X)

In [ ]:
is_outlier

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [ ]:
outliers_count

44

In [ ]:
outliers

array([-2.67240384,  3.00270904,  3.62317101,  3.18867865,  2.55581522,
       -2.82091429,  2.8757892 ,  2.70666036,  3.19514999, -3.40550318,
       -3.39825827,  2.6727295 ,  2.54498296, -2.69447104,  3.19521603,
        2.66372172, -2.77444948,  2.77421152,  2.69992869, -2.84831109,
       -2.83695779, -2.45908227,  3.07802106,  2.89314015, -2.68574682,
       -2.85019494,  2.43399574,  2.44291266, -2.92595937, -2.95911074,
       -3.03966003,  2.77543068, -2.67368414, -2.79965402, -3.0501958 ,
       -2.5437387 ,  3.08550649, -3.17666255, -3.05795476, -3.09826467,
        3.1399469 ,  3.18141942,  2.90564257, -2.89505054])

In [ ]:
# Solução

## Questão 8

Crie um vetor com valores que vão de 1 até 21 de dois em dois, a partir da função arange

In [11]:
import numpy as np
vetor=np.arange(1,22,2)
vetor


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

## Questão 9

Crie um array de 10 com valores aleatórios

In [5]:
import numpy as np
np.random.seed(15)
aleatoria=np.random.randint(-100,100,size=10)
aleatoria

array([ 40,  33,  19,  28,  56,  55,  99, -15,  18,  75])

## Questão 10

Em estatística, a normalização de uma distribuição de dados pode ser feita subtraindo o valor médio da distribuição de cada valor do conjunto de dados, dividindo o resultado pelo desvio-padrão da distribuição. Escreva uma função que normalize os dados recebidos por um array numpy qualquer, conforme descrito anteriormente.

In [9]:
import numpy as np
def normalizado():
    np.random.seed(15)
    array_qualquer=np.random.randint(1,11,size=10)
    media=array_qualquer.mean()
    desvio=array_qualquer.std()
    array_normalizada= (array_qualquer-media)/desvio
    return print('A array é:',array_qualquer,'E a normalizada é:',array_normalizada)
normalizado()

A array é: [9 6 6 8 1 8 6 7 2 8] E a normalizada é: [ 1.15630572 -0.03987261 -0.03987261  0.75757961 -2.03350317  0.75757961
 -0.03987261  0.3588535  -1.63477706  0.75757961]


## Questão 11

Escreva uma função em numpy que receba um array contendo notas de uma turma de 100 estudantes. Considere que a nota de aprovação da turma é 5.0. A função deve retornar, em um array numpy, nesta ordem:
- a média e o desvio-padrão das notas da turma;
- o número de notas maiores que 7.0;
- o número de reprovações da turma;
- a menor nota da turma;
- a maior nota da turma.

In [16]:
import numpy as np
np.random.seed(5)
def notas_turma():
    notas=np.random.randint(0,11,size=100)
    print('A média é:',notas.mean(),'E o desvio padrão é:',notas.std())
    print('O número de notas maiores que 7 é',len(notas[(notas>7)]))
    print('O número de reprovações é de:',len(notas[(notas<5)]))
    print('A menor nota da turma foi:',notas.min())
    print('A maior nota da turma foi:',notas.max())
notas_turma()

A média é: 4.55 E o desvio padrão é: 3.1476181471074285
O número de notas maiores que 7 é 22
O número de reprovações é de: 50
A menor nota da turma foi: 0
A maior nota da turma foi: 10
